# Generated by Django 2.0.7 on 2018-07-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kippoproject',
            name='display_as_active',
            field=models.BooleanField(default=True, help_text='If True, project will be included in the ActiveKippoProject List', verbose_name='Display as Active'),
        ),
    ]
