# Generated by Django 2.1.1 on 2018-10-14 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_kippoproject_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kippoproject',
            name='confidence',
            field=models.PositiveSmallIntegerField(default=80, help_text='0-100, Confidence level of the project proceeding to the next phase', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
