# Generated by Django 2.0.8 on 2018-08-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180720_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcolumn',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Set to True if tasks in column are considered ACTIVE'),
        ),
        migrations.AddField(
            model_name='projectcolumn',
            name='is_done',
            field=models.BooleanField(default=False, help_text='Set to True if tasks in column are considered DONE'),
        ),
    ]
