# Generated by Django 2.2.3 on 2019-07-31 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_collectissuesaction_collectissuesprojectresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectissuesaction',
            name='end_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='collectissuesaction',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
