# Generated by Django 2.2.3 on 2019-08-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190731_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kippoproject',
            name='github_project_url',
        ),
        migrations.AddField(
            model_name='kippoproject',
            name='github_project_html_url',
            field=models.URLField(blank=True, null=True, verbose_name='Github Project HTML URL'),
        ),
    ]
