# Generated by Django 2.0.8 on 2018-08-07 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180805_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kippoproject',
            old_name='column_set',
            new_name='columnset',
        ),
        migrations.RenameField(
            model_name='projectcolumn',
            old_name='column_set',
            new_name='columnset',
        ),
        migrations.AlterUniqueTogether(
            name='projectcolumn',
            unique_together={('columnset', 'name')},
        ),
    ]
