# Generated by Django 2.1.5 on 2019-05-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_kippoprojectstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippomilestone',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
