# Generated by Django 2.2.3 on 2019-08-05 00:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_kippoproject_github_project_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippoproject',
            name='column_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, help_text='If project created through Kippo, this field is populated with column info', null=True),
        ),
    ]
