# Generated by Django 2.2.4 on 2019-08-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectcolumnset_default_column_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcolumn',
            name='github_id',
            field=models.PositiveIntegerField(blank=True, help_text='related github column id assigned on creation', null=True),
        ),
    ]
