# Generated by Django 2.2.9 on 2020-01-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectcolumn_github_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippoproject',
            name='slack_channel_name',
            field=models.CharField(blank=True, default=None, help_text='If given, updates are sent periodically', max_length=80, null=True),
        ),
    ]
