# Generated by Django 2.2.16 on 2021-05-10 00:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0011_projectweeklyeffort"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectweeklyeffort",
            unique_together={("week_start", "project", "user")},
        ),
    ]
