# Generated by Django 2.2.28 on 2022-06-10 02:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0015_auto_20220610_1105"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="kippoprojectusermonthlystatisfactionresult",
            unique_together={("project", "created_by")},
        ),
        migrations.AlterUniqueTogether(
            name="kippoprojectuserstatisfactionresult",
            unique_together={("project", "created_by")},
        ),
    ]
