# Generated by Django 2.2.28 on 2022-06-10 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_auto_20220610_1118"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="kippoprojectusermonthlystatisfactionresult",
            unique_together=set(),
        ),
    ]
