# Generated by Django 2.2.28 on 2022-09-08 07:20

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_auto_20220610_1209"),
    ]

    operations = [
        migrations.AddField(
            model_name="kippoprojectusermonthlystatisfactionresult",
            name="date",
            field=models.DateField(default=projects.models.get_current_month),
        ),
    ]
