# Generated by Django 2.2.28 on 2022-10-18 06:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0018_kippoprojectusermonthlystatisfactionresult_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="kippoprojectusermonthlystatisfactionresult",
            unique_together={("created_by", "project", "date")},
        ),
    ]
