# Generated by Django 5.2.1 on 2025-05-16 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20221018_1551'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activekippoproject',
            options={'verbose_name': 'プロジェクト(実行中)', 'verbose_name_plural': 'プロジェクト(実行中)'},
        ),
        migrations.AlterModelOptions(
            name='kippomilestone',
            options={'verbose_name': 'マイルストーン', 'verbose_name_plural': 'マイルストーン'},
        ),
        migrations.AlterModelOptions(
            name='kippoproject',
            options={'verbose_name': 'プロジェクト', 'verbose_name_plural': 'プロジェクト'},
        ),
        migrations.AlterModelOptions(
            name='projectweeklyeffort',
            options={'verbose_name': 'プロジェクト週間稼働量', 'verbose_name_plural': 'プロジェクト週間稼働量'},
        ),
        migrations.AlterField(
            model_name='collectissuesaction',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collectissuesaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='collectissuesaction',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collectissuesprojectresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='collectissuesprojectresult',
            name='unhandled_issues',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='kippomilestone',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kippomilestone',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Describe the purpose of the milestone', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='kippomilestone',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='column_info',
            field=models.JSONField(blank=True, editable=False, help_text='If project created through Kippo, this field is populated with column info', null=True),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='document_url',
            field=models.URLField(blank=True, default='', help_text='URL of where documents for the projects are maintained', verbose_name='Documentation Location URL'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='github_project_api_url',
            field=models.URLField(blank=True, default='', verbose_name='Github Project api URL (needed for webhook event linking to project)'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='github_project_html_url',
            field=models.URLField(blank=True, default='', verbose_name='Github Project HTML URL'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='problem_definition',
            field=models.TextField(blank=True, default='', help_text='Define the problem that the project is set out to solve.', verbose_name='Project Problem Definition'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='slack_channel_name',
            field=models.CharField(blank=True, default='', help_text='If given, updates are sent periodically', max_length=80),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kippoprojectstatus',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kippoprojectstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kippoprojectstatus',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kippoprojectusermonthlystatisfactionresult',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kippoprojectusermonthlystatisfactionresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kippoprojectusermonthlystatisfactionresult',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kippoprojectuserstatisfactionresult',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kippoprojectuserstatisfactionresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kippoprojectuserstatisfactionresult',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectcolumn',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectweeklyeffort',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectweeklyeffort',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectweeklyeffort',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
