# Generated by Django 5.2.1 on 2025-05-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_activekippoproject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippoproject',
            name='display_in_project_report',
            field=models.BooleanField(default=True, help_text='If True, project will be included in the Project Report Summary', verbose_name='Display in Project Report Summary (slack)'),
        ),
    ]
