# Generated by Django 5.2.1 on 2025-12-15 22:44

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_kippoproject_display_in_project_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kippoproject',
            name='actual_date',
            field=models.DateField(blank=True, help_text='The date the project was actually completed on (not the initial target)', null=True, verbose_name='完了日'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='name',
            field=models.CharField(help_text='Name of the project', max_length=256, unique=True, verbose_name='プロジェクト名'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='start_date',
            field=models.DateField(blank=True, help_text='Date the Project requires engineering resources', null=True, verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='target_date',
            field=models.DateField(blank=True, default=projects.models.get_target_date_default, help_text='Date the Project is planned to be completed by.', null=True, verbose_name='完了予定日'),
        ),
    ]
