# Generated by Django 5.2.1 on 2025-12-24 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_projectmonthlyassignment_delete_projectassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMonthlyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(blank=True, help_text='COST month (defaults to project start_date month)', null=True)),
                ('service', models.CharField(choices=[('AWS', 'AWS'), ('AZURE', 'AZURE'), ('GCP', 'GCP'), ('OTHER', 'OTHER')], max_length=50)),
                ('cost', models.FloatField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('JPY', 'JPY'), ('EUR', 'EUR')], default='USD', max_length=50)),
                ('itemized_cost', models.JSONField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.kippoproject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
