# Generated by Django 5.2.1 on 2026-01-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_projectmonthlycost'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippoproject',
            name='enable_cost_report',
            field=models.BooleanField(default=False, help_text='Set to True if you want to enable cost reporting to the configured slack channel'),
        ),
    ]
