# Generated by Django 5.2.1 on 2026-01-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_kippoproject_enable_cost_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kippoproject',
            name='column_info',
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='slack_channel_name',
            field=models.CharField(blank=True, default='', help_text="Run '/invite {ORG.slack_command_name}' to enable channel notification", max_length=80),
        ),
    ]
