# Generated by Django 5.2.1 on 2026-02-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_remove_kippoproject_column_info'),
    ]

    operations = [
        # First rename the field to preserve existing data
        migrations.RenameField(
            model_name='kippoproject',
            old_name='github_project_api_url',
            new_name='github_project_api_nodeid',
        ),
        # Then alter the field type from URLField to CharField
        migrations.AlterField(
            model_name='kippoproject',
            name='github_project_api_nodeid',
            field=models.CharField(
                blank=True,
                default='',
                max_length=255,
                verbose_name='Github Project API Node ID (GraphQL node ID for ProjectsV2)',
            ),
        ),
    ]
