# Generated by Django 5.2.1 on 2026-05-09 23:16

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_rename_github_project_api_url_to_nodeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcolumnset',
            name='label_category_prefixes',
            field=models.JSONField(blank=True, default=projects.models.category_prefixes_default, help_text='Github Issue Labels Category Prefixes', null=True),
        ),
        migrations.AlterField(
            model_name='projectcolumnset',
            name='label_estimate_prefixes',
            field=models.JSONField(blank=True, default=projects.models.estimate_prefixes_default, help_text='Github Issue Labels Estimate Prefixes', null=True),
        ),
    ]
