# Generated by Django 5.2.1 on 2026-04-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_normalize_kippoproject_slack_channel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kippoproject',
            old_name='document_url',
            new_name='document_folder_url',
        ),
        migrations.AddField(
            model_name='kippoproject',
            name='docbase_tag',
            field=models.CharField(blank=True, default='', help_text='DocBase tag used by the crawler to fetch matching posts', max_length=64, verbose_name='DocBase Tag'),
        ),
        migrations.AddField(
            model_name='kippoproject',
            name='slack_notification_channel_name',
            field=models.CharField(blank=True, default='', help_text='Notification Channel for crawler / batch / development notifications (separate from the conversation channel)', max_length=80),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='slack_channel_name',
            field=models.CharField(blank=True, default='', help_text="Conversation Channel — invite the organization's slack bot to enable channel notification", max_length=80),
        ),
    ]
