# Generated by Django 5.2.1 on 2026-04-30 05:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_kippoorganization_default_columnset'),
        ('projects', '0032_kippoproject_category_choices_close_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='kippoproject',
            name='allocated_staff_days',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated Staff Days needed for Project Completion', null=True, verbose_name='割当工数(人日)'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='category',
            field=models.CharField(choices=[('new-proposal', '新規提案'), ('maintenance', '保守'), ('poc', 'poc'), ('instructor', '講師'), ('r-and-d', 'R&D'), ('PAO', 'PAO'), ('upsell-improvement', '(Upsell) 追加改善・拡張'), ('upsell-new-proposal', '(Upsell) 新規提案'), ('upsell-new-department', '(Upsell) 別部署紹介'), ('other', 'その他')], default='poc', max_length=32, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='close_comment',
            field=models.TextField(blank=True, default='', verbose_name='終了コメント'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='columnset',
            field=models.ForeignKey(help_text='ProjectColumnSet to use if/when a related Github project is created through Kippo', on_delete=django.db.models.deletion.DO_NOTHING, to='projects.projectcolumnset', verbose_name='カラムセット'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='confidence',
            field=models.PositiveSmallIntegerField(default=80, help_text='0-100, Confidence level of the project proceeding to the next phase', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='確度'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='display_as_active',
            field=models.BooleanField(default=True, help_text='If True, project will be included in the ActiveKippoProject List', verbose_name='アクティブとして表示'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='display_in_project_report',
            field=models.BooleanField(default=True, help_text='If True, project will be included in the Project Report Summary', verbose_name='プロジェクトレポートサマリ(Slack)に表示'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='docbase_tag',
            field=models.CharField(blank=True, default='', help_text='DocBase tag used by the crawler to fetch matching posts', max_length=64, verbose_name='DocBaseタグ'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='document_folder_url',
            field=models.URLField(blank=True, default='', help_text='URL of where documents for the projects are maintained', verbose_name='ドキュメント保管URL'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='enable_cost_report',
            field=models.BooleanField(default=False, help_text='Set to True if you want to enable cost reporting to the configured slack channel', verbose_name='コストレポート有効化'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='github_project_api_nodeid',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='GitHubプロジェクトAPIノードID'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='github_project_html_url',
            field=models.URLField(blank=True, default='', verbose_name='GitHubプロジェクトのHTML URL'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Manually set when project is complete', verbose_name='プロジェクト終了済み'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.kippoorganization', verbose_name='組織'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='parent_project',
            field=models.ForeignKey(blank=True, help_text='Original (parent) project for upsell projects', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upsell_children', to='projects.kippoproject', verbose_name='親プロジェクト'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='phase',
            field=models.CharField(choices=[('anon-project', 'Non-Project'), ('lead-evaluation', 'Lead Evaluation'), ('project-proposal', 'Project Proposal Preparation'), ('project-development', 'Project Development')], default='lead-evaluation', help_text='State or phase of the project', max_length=150, verbose_name='フェーズ'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='problem_definition',
            field=models.TextField(blank=True, default='', help_text='Define the problem that the project is set out to solve.', verbose_name='プロジェクト課題定義'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='project_manager',
            field=models.ForeignKey(blank=True, help_text='Project Manager assigned to the project', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='プロジェクトマネージャー'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='slack_channel_name',
            field=models.CharField(blank=True, default='', help_text="Conversation Channel — invite the organization's slack bot to enable channel notification", max_length=80, verbose_name='Slack会話チャンネル名'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='slack_notification_channel_name',
            field=models.CharField(blank=True, default='', help_text='Notification Channel for crawler / batch / development notifications (separate from the conversation channel)', max_length=80, verbose_name='Slack通知チャンネル名'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='survey_issued',
            field=models.BooleanField(default=False, help_text='Update when survey is issued!', verbose_name='アンケート発行済み'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='survey_issued_datetime',
            field=models.DateTimeField(editable=False, help_text='Updated when "survey_issued" flag is set', null=True, verbose_name='アンケート発行日時'),
        ),
    ]
