# Generated by Django 5.2.1 on 2026-05-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_kippoproject_japanese_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kippoproject',
            name='category',
            field=models.CharField(choices=[('new-proposal', '新規提案'), ('maintenance', '保守'), ('poc', 'poc'), ('instructor', '講師'), ('r-and-d', 'R&D'), ('PAO', 'PAO'), ('upsell-improvement', '(Upsell) 追加改善・拡張'), ('upsell-new-proposal', '(Upsell) 新規提案'), ('upsell-new-department', '(Upsell) 別部署紹介'), ('other', 'その他')], default='new-proposal', max_length=32, verbose_name='カテゴリ'),
        ),
    ]
