# Generated by Django 5.2.1 on 2026-05-10 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_alter_projectcolumnset_label_category_prefixes_and_more'),
        ('projects', '0033_alter_kippoproject_category'),
    ]

    operations = [
    ]
