# Generated by Django 5.2.1 on 2026-05-12 05:07

import commons.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_alter_projectcolumnset_label_category_prefixes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kippoproject',
            name='docbase_tag',
            field=commons.fields.CommaSeparatedCharField(blank=True, default='', help_text="Comma-separated DocBase tags used by the crawler to fetch matching posts (e.g. 'foo,bar')", max_length=255, verbose_name='DocBaseタグ'),
        ),
    ]
