# Generated by Django 5.2.1 on 2026-05-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_kippocustomer_kippoproject_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippocustomer',
            name='document_url',
            field=models.URLField(blank=True, default='', help_text='Link to customer-related documents (folder, drive, wiki, etc.)', verbose_name='ドキュメントURL'),
        ),
    ]
