# Generated by Django 5.2.1 on 2026-05-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_kippocustomer_kippoproject_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippoproject',
            name='billing_date',
            field=models.DateField(blank=True, help_text='Date the project is billed. Defaults to the target date when left blank.', null=True, verbose_name='請求日'),
        ),
    ]
