# Generated by Django 5.2.1 on 2026-06-01 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_kippoproject_billing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectweeklyeffort',
            name='hours',
            field=models.SmallIntegerField(help_text="Actual effort in hours performed on the project for the given 'week start' (0-168)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)]),
        ),
    ]
