# Generated by Django 5.2.1 on 2026-06-22 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0040_issue33_pending_consolidated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmonthlyassignment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="projectassignment_project", to="projects.kippoproject"
            ),
        ),
        migrations.AlterField(
            model_name="projectweeklyeffort",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="projectweeklyeffort_project", to="projects.kippoproject"
            ),
        ),
    ]
