# Generated by Django 5.2.1 on 2026-06-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_issue36_phase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippoproject',
            name='billing_method',
            field=models.CharField(choices=[('delivery', '納品'), ('monthly', '月額')], default='delivery', help_text="Billing method: 'delivery' (納品, billed once) or 'monthly' (月額, recurring per month).", max_length=20, verbose_name='請求方法'),
        ),
        migrations.AddField(
            model_name='kippoproject',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text='Last day of the contract period. Required for monthly-billing revenue accrual.', null=True, verbose_name='契約期間終了'),
        ),
        migrations.AddField(
            model_name='kippoproject',
            name='contract_start_date',
            field=models.DateField(blank=True, help_text='First day of the contract period. Required for monthly-billing revenue accrual.', null=True, verbose_name='契約期間開始'),
        ),
        migrations.AddField(
            model_name='kippoproject',
            name='monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text="Monthly billed amount (JPY). Only meaningful when billing_method is 'monthly'.", max_digits=12, null=True, verbose_name='月額金額'),
        ),
    ]
