# Generated by Django 5.2.1 on 2026-06-18 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_kippoorganization_weekly_effort_close_offset_days'),
        ('projects', '0041_issue36_phase_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KippoProjectContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('closed_datetime', models.DateTimeField(editable=False, null=True)),
                ('billing_type', models.CharField(choices=[('delivery', '納品'), ('monthly', '月額')], default='delivery', help_text="'delivery' (納品, amount billed once at the contract end_date) or 'monthly' (月額, amount accrues month-end per month).", max_length=20, verbose_name='請求方法')),
                ('amount', models.DecimalField(decimal_places=0, help_text="JPY. Contract total for 'delivery'; per-month amount for 'monthly'.", max_digits=12, verbose_name='金額')),
                ('start_date', models.DateField(blank=True, help_text='Contract period start. Auto-populated from the project start_date when left blank.', null=True, verbose_name='契約開始日')),
                ('end_date', models.DateField(blank=True, help_text='Contract period end. Auto-populated from the project target_date when left blank.', null=True, verbose_name='契約終了日')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='備考')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='projects.kippoproject')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '契約',
                'verbose_name_plural': '契約',
                'ordering': ('created_datetime',),
            },
        ),
        migrations.CreateModel(
            name='KippoProjectBillingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('closed_datetime', models.DateTimeField(editable=False, null=True)),
                ('billing_date', models.DateField(help_text='Date the entry is billed/recognized. Monthly-generated entries use the month-end (月末) date.', verbose_name='請求日')),
                ('amount', models.DecimalField(decimal_places=0, help_text='Billed amount (JPY).', max_digits=12, verbose_name='金額')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='備考')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_entries', to='projects.kippoproject')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(blank=True, help_text='Contract the entry was generated from (blank for manually added entries).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_entries', to='projects.kippoprojectcontract')),
            ],
            options={
                'verbose_name': '請求エントリ',
                'verbose_name_plural': '請求エントリ',
                'ordering': ('billing_date',),
                'constraints': [models.UniqueConstraint(fields=('project', 'billing_date'), name='unique_billingentry_project_billing_date')],
            },
        ),
        migrations.CreateModel(
            name='ProjectWeeklyEffortUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('closed_datetime', models.DateTimeField(editable=False, null=True)),
                ('week_start', models.DateField(help_text='Unlocked Effort Week Start (MONDAY)')),
                ('reason', models.TextField(help_text='アンロック申請理由 (DCAA: 締め後編集には記録された正当な理由が必要)')),
                ('approved_datetime', models.DateTimeField(blank=True, default=None, help_text='承認日時 (未設定 = 承認待ち)', null=True)),
                ('expires_datetime', models.DateTimeField(blank=True, default=None, help_text='再ロック期限: 承認時に設定され、この日時を過ぎると編集不可に戻る', null=True)),
                ('approved_by', models.ForeignKey(blank=True, default=None, help_text='承認した組織admin (未設定 = 承認待ち)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectweeklyeffortunlock_approved_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectweeklyeffortunlock_organization', to='accounts.kippoorganization')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectweeklyeffortunlock_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'プロジェクト週間稼働アンロック',
                'verbose_name_plural': 'プロジェクト週間稼働アンロック',
                'unique_together': {('organization', 'user', 'week_start')},
            },
        ),
    ]
