# Generated by Django 5.2.1 on 2026-06-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_issue31_billing_contract_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kippoprojectbillingentry',
            name='billing_date',
            field=models.DateField(help_text='Date the entry is billed/recognized. Monthly-generated entries use the month-end (月末) date.', verbose_name='請求日'),
        ),
        migrations.AlterField(
            model_name='kippoprojectcontract',
            name='billing_type',
            field=models.CharField(choices=[('delivery', '納品'), ('monthly', '月額')], default='delivery', help_text="'delivery' (納品, amount billed once at the contract end_date) or 'monthly' (月額, amount accrues month-end per month).", max_length=20, verbose_name='請求方法'),
        ),
    ]
