# Generated by Django 5.2.1 on 2026-06-10 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_issue31_billing_monthly_revenue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KippoProjectBillingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('closed_datetime', models.DateTimeField(editable=False, null=True)),
                ('billing_date', models.DateField(help_text='Date the entry is billed/recognized. Monthly-generated entries use the first day of the month.', verbose_name='請求日')),
                ('amount', models.DecimalField(decimal_places=0, help_text='Billed amount (JPY).', max_digits=12, verbose_name='金額')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='備考')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_entries', to='projects.kippoproject')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '請求エントリ',
                'verbose_name_plural': '請求エントリ',
                'ordering': ('billing_date',),
                'constraints': [models.UniqueConstraint(fields=('project', 'billing_date'), name='unique_billingentry_project_billing_date')],
            },
        ),
    ]
