# Generated by Django 5.2.1 on 2026-06-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_sync_billing_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippoproject',
            name='introduction',
            field=models.TextField(blank=True, default='', help_text='Short introduction/description of the project, shown in the project list and detail (kippo#29 / T07).', verbose_name='プロジェクト紹介文'),
        ),
    ]
