# Generated by Django 5.2.1 on 2026-06-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_billingentry_received_and_drop_project_billing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmonthlyassignment',
            name='role',
            field=models.CharField(blank=True, choices=[('developer', 'developer'), ('project_manager', 'project_manager'), ('tester', 'tester')], default='', help_text="Billing-rate role for effort-based billing; selects the project's ProjectAssignmentRate for this user's logged effort. Empty falls back to the developer rate.", max_length=50),
        ),
    ]
