# Generated by Django 5.2.1 on 2026-06-18 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_kippoorganization_weekly_effort_close_offset_days'),
        ('projects', '0043_sync_billing_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWeeklyEffortUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('closed_datetime', models.DateTimeField(editable=False, null=True)),
                ('week_start', models.DateField(help_text='Unlocked Effort Week Start (MONDAY)')),
                ('reason', models.TextField(help_text='アンロック申請理由 (DCAA: 締め後編集には記録された正当な理由が必要)')),
                ('approved_datetime', models.DateTimeField(blank=True, default=None, help_text='承認日時 (未設定 = 承認待ち)', null=True)),
                ('expires_datetime', models.DateTimeField(blank=True, default=None, help_text='再ロック期限: 承認時に設定され、この日時を過ぎると編集不可に戻る', null=True)),
                ('approved_by', models.ForeignKey(blank=True, default=None, help_text='承認した組織admin (未設定 = 承認待ち)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectweeklyeffortunlock_approved_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectweeklyeffortunlock_organization', to='accounts.kippoorganization')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectweeklyeffortunlock_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'プロジェクト週間稼働アンロック',
                'verbose_name_plural': 'プロジェクト週間稼働アンロック',
                'unique_together': {('organization', 'user', 'week_start')},
            },
        ),
    ]
