# Generated by Django 5.2.1 on 2026-06-12 01:45

import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_kippoorganization_default_columnset'),
        ('projects', '0043_sync_billing_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWeeklyEffortUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('closed_datetime', models.DateTimeField(editable=False, null=True)),
                ('week_start', models.DateField(help_text='Unlocked Effort Week Start (MONDAY)')),
                ('expires_datetime', models.DateTimeField(default=projects.models.default_unlock_expires_datetime, help_text='アンロックの有効期限 (この日時まで編集可能)')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectweeklyeffortunlock_organization', to='accounts.kippoorganization')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectweeklyeffortunlock_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'プロジェクト週間稼働アンロック',
                'verbose_name_plural': 'プロジェクト週間稼働アンロック',
                'unique_together': {('organization', 'user', 'week_start')},
            },
        ),
    ]
