# Generated by Django 5.2.1 on 2026-06-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_remove_kippoproject_billing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippoprojectbillingentry',
            name='is_received',
            field=models.BooleanField(default=False, help_text='True once payment for this billing entry has been received.', verbose_name='入金済'),
        ),
        migrations.AddField(
            model_name='kippoprojectbillingentry',
            name='received_datetime',
            field=models.DateTimeField(blank=True, help_text='When payment was received. Auto-set when is_received is enabled; cleared when disabled.', null=True, verbose_name='入金日時'),
        ),
    ]
