# Generated by Django 5.2.1 on 2026-06-18 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_issue33_weekly_effort_unlock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectweeklyeffortunlock',
            name='approved_by',
            field=models.ForeignKey(blank=True, default=None, help_text='承認した組織admin (未設定 = 承認待ち)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectweeklyeffortunlock_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectweeklyeffortunlock',
            name='approved_datetime',
            field=models.DateTimeField(blank=True, default=None, help_text='承認日時 (未設定 = 承認待ち)', null=True),
        ),
        migrations.AddField(
            model_name='projectweeklyeffortunlock',
            name='reason',
            field=models.TextField(default='', help_text='アンロック申請理由 (DCAA: 締め後編集には記録された正当な理由が必要)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectweeklyeffortunlock',
            name='expires_datetime',
            field=models.DateTimeField(blank=True, default=None, help_text='再ロック期限: 承認時に設定され、この日時を過ぎると編集不可に戻る', null=True),
        ),
    ]
