# Generated by Django 5.2.1 on 2026-06-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_projectmonthlyassignment_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippoprojectcontract',
            name='pricing_basis',
            field=models.CharField(choices=[('fixed', '固定'), ('effort', '実績')], default='fixed', help_text="How each billed amount is computed: 'fixed' (固定, the contract total_amount) or 'effort' (実績, actual logged effort × role rate — time-&-materials). When 'effort', total_amount is an optional cap (上限) and may be left blank.", max_length=20, verbose_name='料金体系'),
        ),
        migrations.AlterField(
            model_name='kippoprojectcontract',
            name='billing_type',
            field=models.CharField(choices=[('delivery', '納品'), ('monthly', '月額')], default='delivery', help_text="When revenue is billed: 'delivery' (納品, once at the contract end_date) or 'monthly' (月額, each month-end across the contract period).", max_length=20, verbose_name='請求方法'),
        ),
        migrations.AlterField(
            model_name='kippoprojectcontract',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text="JPY. Contract total for 'fixed' pricing (required; for 'monthly' it is split evenly across the contract months with the remainder on the final month). For 'effort' pricing it is an optional cap (上限) and may be left blank.", max_digits=12, null=True, verbose_name='契約金額'),
        ),
    ]
