# Generated by Django 5.2.1 on 2026-06-26 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_kippoorganization_timezone_name'),
        ('projects', '0045_kippoprojectcontract_pricing_basis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='kippoprojectorganizationcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'label'), name='uniq_org_category_label'),
        ),
        migrations.AddConstraint(
            model_name='kippoprojectorganizationcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('label',), name='uniq_global_category_label'),
        ),
    ]
