# Generated by Django 5.2.1 on 2026-06-26 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_kippoorganization_timezone_name'),
        ('projects', '0045_kippoprojectcontract_pricing_basis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='kippoproject',
            name='phase',
            field=models.CharField(choices=[('keep-in-touch', 'KIT'), ('proposing-low', '提案(低)'), ('proposing-mid', '提案(中)'), ('proposing-high', '提案(高)'), ('verbal-order', '口頭受注'), ('under-contract', '契約(稼働中)'), ('completed', '完了'), ('lost', '失注')], default='proposing-low', help_text='State or phase of the project', max_length=150, verbose_name='フェーズ'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='problem_definition',
            field=models.TextField(blank=True, default='', help_text='Define the problem that the project is set out to solve.', verbose_name='プロジェクト紹介'),
        ),
        migrations.AddConstraint(
            model_name='kippoprojectorganizationcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'label'), name='uniq_org_category_label'),
        ),
        migrations.AddConstraint(
            model_name='kippoprojectorganizationcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('label',), name='uniq_global_category_label'),
        ),
    ]
