# Generated by Django 5.2.1 on 2026-07-02 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_alter_kippoproject_phase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projectmonthlyassignment',
            index=models.Index(fields=['month'], name='projects_pr_month_c00275_idx'),
        ),
    ]
