# Generated by Django 5.2.1 on 2026-06-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_kippoprojectorganizationcategory_uniq_org_category_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kippoproject',
            name='phase',
            field=models.CharField(choices=[('keep-in-touch', 'KIT'), ('proposing-low', '提案(低)'), ('proposing-mid', '提案(中)'), ('proposing-high', '提案(高)'), ('verbal-order', '口頭受注'), ('under-contract', '契約(稼働中)'), ('completed', '完了'), ('lost', '失注')], default='proposing-low', help_text='State or phase of the project', max_length=150, verbose_name='フェーズ'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='problem_definition',
            field=models.TextField(blank=True, default='', help_text='Define the problem that the project is set out to solve.', verbose_name='プロジェクト紹介'),
        ),
    ]
