# Generated by Django 5.2.1 on 2026-07-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_projectmonthlyassignment_projects_pr_month_c00275_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippoprojectcontract',
            name='estimated_monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='JPY. Provisional (仮) monthly amount for effort + monthly contracts (kippo#46): every contract month is billed this amount up front, then corrected to actuals (実績) via the true-up admin action before the entry is received. Blank bills logged actuals directly.', max_digits=12, null=True, verbose_name='仮月額'),
        ),
    ]
