# Generated by Django 5.2.1 on 2026-07-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_seed_org_categories_and_remap_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippoprojectorganizationcategory',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Auto-selected category for new projects in this organization (at most one per organization)', verbose_name='デフォルト'),
        ),
    ]
