# Generated by Django 5.2.1 on 2026-07-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_kippoprojectorganizationcategory_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesKippoProject',
            fields=[
            ],
            options={
                'verbose_name': 'プロジェクト(営業中)',
                'verbose_name_plural': 'プロジェクト(営業中)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.kippoproject',),
        ),
    ]
