# Generated by Django 5.2.1 on 2026-07-08 10:04

import commons.fields
import django.core.validators
import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_kippocustomer_contract_folder_url'),
        ('projects', '0050_saleskippoproject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kippoproject',
            name='lead_source',
            field=models.CharField(blank=True, choices=[('sunx', 'SUNX経由'), ('info', 'info'), ('employee-referral', '社員紹介'), ('customer-referral', '顧客紹介'), ('continuation', '継続')], default='', help_text='案件のリード獲得元（任意）', max_length=32, verbose_name='リード'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='actual_date',
            field=models.DateField(blank=True, help_text='プロジェクトが実際に完了した日（当初の予定日ではありません）', null=True, verbose_name='完了日'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='allocated_staff_days',
            field=models.PositiveIntegerField(blank=True, help_text='プロジェクト完了に必要な見積工数（人日）', null=True, verbose_name='割当工数(人日)'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='columnset',
            field=models.ForeignKey(help_text='Kippoを通じて関連するGitHubプロジェクトを作成する際に使用するProjectColumnSet', on_delete=django.db.models.deletion.DO_NOTHING, to='projects.projectcolumnset', verbose_name='カラムセット'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='confidence',
            field=models.PositiveSmallIntegerField(default=30, editable=False, help_text='0〜100。フェーズから自動算出されます（読み取り専用）', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='確度'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='このプロジェクトの納品先となる顧客（任意）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='customers.kippocustomer', verbose_name='顧客'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='display_as_active',
            field=models.BooleanField(default=True, help_text='Trueの場合、アクティブプロジェクト一覧に表示されます', verbose_name='アクティブとして表示'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='display_in_project_report',
            field=models.BooleanField(default=True, help_text='Trueの場合、プロジェクトレポートサマリに表示されます', verbose_name='プロジェクトレポートサマリ(Slack)に表示'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='docbase_tag',
            field=commons.fields.CommaSeparatedCharField(blank=True, default='', help_text="クローラーが該当する投稿を取得するために使用するカンマ区切りのDocBaseタグ（例: 'foo,bar'）", max_length=255, verbose_name='DocBaseタグ'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='document_folder_url',
            field=models.URLField(blank=True, default='', help_text='プロジェクトのドキュメントを保管しているURL', verbose_name='ドキュメント保管URL'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='enable_cost_report',
            field=models.BooleanField(default=False, help_text='設定済みのSlackチャンネルへコストレポートを送信する場合はTrueに設定します', verbose_name='コストレポート有効化'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='プロジェクト完了時に手動で設定します', verbose_name='プロジェクト終了済み'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='name',
            field=models.CharField(help_text='プロジェクトの名称', max_length=256, unique=True, verbose_name='プロジェクト名'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='parent_project',
            field=models.ForeignKey(blank=True, help_text='継続プロジェクトの元（親）プロジェクト', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continuation_children', to='projects.kippoproject', verbose_name='親プロジェクト'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='phase',
            field=models.CharField(choices=[('keep-in-touch', 'KIT'), ('proposing-low', '提案(低)'), ('proposing-mid', '提案(中)'), ('proposing-high', '提案(高)'), ('verbal-order', '口頭受注'), ('under-contract', '契約(稼働中)'), ('completed', '完了'), ('lost', '失注')], default='proposing-low', help_text='プロジェクトの状態（フェーズ）', max_length=150, verbose_name='フェーズ'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='problem_definition',
            field=models.TextField(blank=True, default='', help_text='このプロジェクトが解決しようとする課題を定義します', verbose_name='プロジェクト紹介'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='project_manager',
            field=models.ForeignKey(blank=True, help_text='プロジェクトに割り当てるプロジェクトマネージャー', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='プロジェクトマネージャー'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='slack_channel_name',
            field=models.CharField(blank=True, default='', help_text='会話用チャンネル。組織のSlackボットを招待するとチャンネル通知が有効になります', max_length=80, verbose_name='Slack会話チャンネル名'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='slack_notification_channel_name',
            field=models.CharField(blank=True, default='', help_text='クローラー・バッチ・開発通知用のチャンネル（会話用チャンネルとは別）', max_length=80, verbose_name='Slack通知チャンネル名'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='start_date',
            field=models.DateField(blank=True, help_text='プロジェクトがエンジニアリングリソースを必要とする日', null=True, verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='survey_issued',
            field=models.BooleanField(default=False, help_text='アンケートを発行したら更新してください', verbose_name='アンケート発行済み'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='survey_issued_datetime',
            field=models.DateTimeField(editable=False, help_text='「アンケート発行済み」フラグが設定されたときに更新されます', null=True, verbose_name='アンケート発行日時'),
        ),
        migrations.AlterField(
            model_name='kippoproject',
            name='target_date',
            field=models.DateField(blank=True, default=projects.models.get_target_date_default, help_text='プロジェクトの完了予定日', null=True, verbose_name='完了予定日'),
        ),
    ]
