# Generated by Django 5.2.1 on 2026-07-10 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_kippocustomer_contract_folder_url'),
        ('projects', '0053_contract_monthly_amount_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippoprojectcontract',
            name='billed_to',
            field=models.ForeignKey(blank=True, help_text="Customer invoiced for this contract. Defaults to the project's customer (顧客); set explicitly when billing goes to a different customer.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_contracts', to='customers.kippocustomer', verbose_name='請求先'),
        ),
    ]
