# Generated by Django 5.2.1 on 2026-07-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_kippoprojectcontract_billed_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kippoproject',
            name='lead_source',
            field=models.CharField(blank=True, choices=[('sunx', 'SUNX経由'), ('info', 'info'), ('employee-referral', '社員紹介'), ('customer-referral', '顧客紹介'), ('partner-introduction', 'パートナー紹介'), ('continuation', '継続')], default='', help_text='案件のリード獲得元（任意）', max_length=32, verbose_name='リード'),
        ),
    ]
