# Generated by Django 5.2.1 on 2026-07-14 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_kippocustomer_contract_folder_url'),
        ('projects', '0055_alter_kippoproject_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kippoprojectcontract',
            name='billed_to',
            field=models.ForeignKey(blank=True, help_text='請求先の顧客。未入力の場合はプロジェクトの顧客。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_contracts', to='customers.kippocustomer', verbose_name='請求先'),
        ),
        migrations.AlterField(
            model_name='kippoprojectcontract',
            name='billing_type',
            field=models.CharField(choices=[('delivery', '納品'), ('monthly', '月額')], default='delivery', help_text='請求するタイミング。納品: 契約終了日に一括。月額: 契約期間の各月末。', max_length=20, verbose_name='請求方法'),
        ),
        migrations.AlterField(
            model_name='kippoprojectcontract',
            name='end_date',
            field=models.DateField(blank=True, help_text='未入力の場合はプロジェクトの完了予定日を自動設定。', null=True, verbose_name='契約終了日'),
        ),
        migrations.AlterField(
            model_name='kippoprojectcontract',
            name='estimated_monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='実績 × 月額の契約のみ。各月をこの暫定額で請求し、入金前に「請求エントリを実績に修正」で実績額へ修正。未入力の場合は実績額をそのまま請求。', max_digits=12, null=True, verbose_name='月額'),
        ),
        migrations.AlterField(
            model_name='kippoprojectcontract',
            name='pricing_basis',
            field=models.CharField(choices=[('fixed', '固定'), ('effort', '実績')], default='fixed', help_text='請求額の算出方法。固定: 契約金額。実績: 実績工数 × ロール単価。', max_length=20, verbose_name='料金体系'),
        ),
        migrations.AlterField(
            model_name='kippoprojectcontract',
            name='start_date',
            field=models.DateField(blank=True, help_text='未入力の場合はプロジェクトの開始日を自動設定。', null=True, verbose_name='契約開始日'),
        ),
        migrations.AlterField(
            model_name='kippoprojectcontract',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='契約総額(円)。固定の場合は必須(月額請求では各月に均等配分し、端数は最終月)。実績の場合は任意(上限)。', max_digits=12, null=True, verbose_name='契約金額'),
        ),
    ]
