# Generated by Django 2.0.7 on 2018-07-20 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octocat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubrepositorylabelsdefinition',
            name='closed_datetime',
        ),
        migrations.RemoveField(
            model_name='githubrepositorylabelsdefinition',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='githubrepositorylabelsdefinition',
            name='updated_by',
        ),
    ]
