# Generated by Django 2.2.3 on 2019-08-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octocat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubwebhookevent',
            name='related_project',
        ),
        migrations.AddField(
            model_name='githubwebhookevent',
            name='event_type',
            field=models.CharField(help_text='X-Github-Event value', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='githubwebhookevent',
            name='state',
            field=models.CharField(choices=[('unprocessed', 'unprocessed'), ('processing', 'processing'), ('error', 'error'), ('processed', 'processed')], default='unprocessed', max_length=15),
        ),
    ]
