# Generated by Django 2.2.3 on 2019-08-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octocat', '0002_auto_20190803_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubwebhookevent',
            name='event_type',
            field=models.CharField(help_text='X-Github-Event value (See: https://developer.github.com/v3/activity/events/types/)', max_length=25, null=True),
        ),
    ]
