# Generated by Django 2.1.3 on 2019-01-16 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_kippouser_is_github_outside_collaborator'),
        ('octocat', '0002_auto_20180927_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubrepository',
            name='project',
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.KippoOrganization'),
            preserve_default=False,
        ),
    ]
