# Generated by Django 2.2.4 on 2019-08-08 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190730_0421'),
        ('octocat', '0003_auto_20190805_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepositorylabelset',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization to which the labelset belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.KippoOrganization'),
        ),
    ]
