# Generated by Django 2.2.9 on 2020-01-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octocat', '0004_githubrepositorylabelset_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubwebhookevent',
            name='state',
            field=models.CharField(choices=[('unprocessed', 'unprocessed'), ('processing', 'processing'), ('error', 'error'), ('processed', 'processed'), ('ignore', 'ignore')], default='unprocessed', max_length=15),
        ),
    ]
