# Generated by Django 2.2.10 on 2020-03-04 04:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("octocat", "0005_auto_20200120_0926")]

    operations = [
        migrations.AlterField(model_name="githubwebhookevent", name="event", field=django.contrib.postgres.fields.jsonb.JSONField(editable=False))
    ]
