# Generated by Django 2.2.16 on 2020-10-23 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("octocat", "0007_auto_20200330_1202"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubmilestone",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                help_text="Related Kippo Milestone",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="projects.KippoMilestone",
                verbose_name="Kippo Milestone",
            ),
        ),
    ]
