# Generated by Django 5.2.1 on 2026-05-09 23:16

import django.db.models.deletion
import octocat.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octocat', '0008_auto_20201023_1804'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubaccesstoken',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='githubaccesstoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='githubaccesstoken',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='githubmilestone',
            name='api_url',
            field=models.URLField(blank=True, default='', help_text='Github Repository Milestone API URL', verbose_name='Github Milestone API URL'),
        ),
        migrations.AlterField(
            model_name='githubmilestone',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='githubmilestone',
            name='html_url',
            field=models.URLField(blank=True, default='', help_text='Github Repository Milestone HTML URL', verbose_name='Github Milestone HTML URL'),
        ),
        migrations.AlterField(
            model_name='githubmilestone',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='githuborganizationalwebhook',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='githuborganizationalwebhook',
            name='events',
            field=models.JSONField(default=octocat.models.webhook_events_default, help_text='Github webhook event(s)'),
        ),
        migrations.AlterField(
            model_name='githuborganizationalwebhook',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='githubrepositorylabelset',
            name='labels',
            field=models.JSONField(help_text='Labels defined in the format: [{"name": "category:X", "description": "", "color": "AED6F1"},]'),
        ),
        migrations.AlterField(
            model_name='githubwebhookevent',
            name='event',
            field=models.JSONField(editable=False),
        ),
        migrations.AlterField(
            model_name='githubwebhookevent',
            name='event_type',
            field=models.CharField(blank=True, default='', help_text='X-Github-Event value (See: https://developer.github.com/v3/activity/events/types/)', max_length=25),
        ),
        migrations.AlterField(
            model_name='githubwebhookevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
