# Generated by Django 5.2.1 on 2026-05-10 04:42

import octocat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octocat', '0009_issue9_project_external_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githuborganizationalwebhook',
            name='events',
            field=models.JSONField(default=octocat.models.webhook_events_default, help_text='Github webhook event(s)'),
        ),
    ]
