# Generated by Django 5.2.1 on 2026-05-10 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octocat', '0009_alter_githubaccesstoken_created_by_and_more'),
        ('projects', '0029_alter_projectcolumnset_label_category_prefixes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepository',
            name='project',
            field=models.ForeignKey(blank=True, help_text='KippoProject this repository belongs to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_repositories', to='projects.kippoproject'),
        ),
    ]
