# Generated by Django 5.2.1 on 2026-05-10 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octocat', '0009_alter_githubaccesstoken_created_by_and_more'),
        ('octocat', '0009_issue9_project_external_resources'),
    ]

    operations = [
    ]
