# Generated by Django 5.2.1 on 2025-12-15 23:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0023_projectassignmentrate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('display_id_number', models.PositiveIntegerField(default=0, editable=False)),
                ('category', models.CharField(choices=[('assumption', '前提条件'), ('constraint', '制約事項')], default='assumption')),
                ('is_internal', models.BooleanField(default=False, help_text='社内のみの場合設定')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.kippoproject')),
            ],
            options={
                'verbose_name': 'Assumption',
                'verbose_name_plural': 'Assumptions',
            },
        ),
        migrations.CreateModel(
            name='ProjectBusinessRequirementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.kippoproject')),
            ],
            options={
                'verbose_name': 'Business Requirement Category',
                'verbose_name_plural': 'Business Requirement Categories',
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectBusinessRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('display_id_number', models.PositiveIntegerField(default=0, editable=False)),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.kippoproject')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.projectbusinessrequirementcategory')),
            ],
            options={
                'verbose_name': 'Business Requirement',
                'verbose_name_plural': 'Business Requirements',
            },
        ),
        migrations.CreateModel(
            name='ProjectBusinessRequirementComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('closed_datetime', models.DateTimeField(editable=False, null=True)),
                ('comment', models.TextField()),
                ('is_resolved', models.BooleanField(default=False, help_text='is_resolved is only relevant for top-level comments')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='requirements.projectbusinessrequirementcomment')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.projectbusinessrequirement')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Requirement Comment',
                'verbose_name_plural': 'Business Requirement Comments',
            },
        ),
        migrations.CreateModel(
            name='ProjectProblemDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('display_id_number', models.PositiveIntegerField(default=0, editable=False)),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.kippoproject')),
            ],
            options={
                'verbose_name': 'Problem Definition',
                'verbose_name_plural': 'Problem Definitions',
            },
        ),
        migrations.AddField(
            model_name='projectbusinessrequirement',
            name='problems',
            field=models.ManyToManyField(blank=True, to='requirements.projectproblemdefinition'),
        ),
        migrations.CreateModel(
            name='ProjectTechnicalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('display_id_number', models.PositiveIntegerField(default=0, editable=False)),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, default='')),
                ('business_requirements', models.ManyToManyField(blank=True, to='requirements.projectbusinessrequirement')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.kippoproject')),
            ],
            options={
                'verbose_name': 'Technical Requirement',
                'verbose_name_plural': 'Technical Requirements',
            },
        ),
        migrations.CreateModel(
            name='ProjectBusinessRequirementEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('closed_datetime', models.DateTimeField(editable=False, null=True)),
                ('days', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(30.0)])),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)])),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='requirements.projecttechnicalrequirement')),
            ],
            options={
                'verbose_name': 'Requirement Estimate',
                'verbose_name_plural': 'Requirement Estimates',
            },
        ),
        migrations.CreateModel(
            name='ProjectTechnicalRequirementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.kippoproject')),
            ],
            options={
                'verbose_name': 'Technical Requirement Category',
                'verbose_name_plural': 'Technical Requirement Categories',
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='projecttechnicalrequirement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.projecttechnicalrequirementcategory'),
        ),
        migrations.CreateModel(
            name='ProjectTechnicalRequirementComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('closed_datetime', models.DateTimeField(editable=False, null=True)),
                ('comment', models.TextField()),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='requirements.projecttechnicalrequirementcomment')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.projecttechnicalrequirement')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technical Requirement Comment',
                'verbose_name_plural': 'Technical Requirement Comments',
            },
        ),
        migrations.CreateModel(
            name='ProjectTechnicalRequirementGithubIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('technical_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.projecttechnicalrequirement')),
            ],
            options={
                'verbose_name': 'Technical Requirement GitHub Issue',
                'verbose_name_plural': 'Technical Requirement GitHub Issues',
            },
        ),
    ]
