# Generated by Django 5.2.1 on 2025-12-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttechnicalrequirement',
            name='include_in_estimate',
            field=models.BooleanField(default=True, help_text='見積もり計算には、含むかどうか'),
        ),
    ]
