# Generated by Django 2.1.1 on 2018-09-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippotaskstatus',
            name='state_priority',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='The priority of the task within the given state (column) [smaller is better]', null=True),
        ),
    ]
