# Generated by Django 2.2.3 on 2019-08-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kippotaskstatus',
            name='tags',
            field=models.JSONField(blank=True, help_text='Any tags/labels related to the current task status', null=True),
        ),
    ]
