# Generated by Django 2.2.4 on 2019-08-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190805_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippotask',
            name='project_card_id',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='CardId when task belongs to a specific Github Project', null=True),
        ),
    ]
