# Generated by Django 2.2.10 on 2020-03-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("projects", "0009_kippoproject_slack_channel_name"), ("tasks", "0003_kippotask_project_card_id")]

    operations = [
        migrations.AlterModelOptions(name="kippotask", options={"get_latest_by": "created_datetime"}),
        migrations.AlterUniqueTogether(name="kippotask", unique_together={("project", "github_issue_api_url")}),
    ]
