# Generated by Django 2.2.10 on 2020-03-30 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tasks", "0004_auto_20200302_1522")]

    operations = [
        migrations.AlterField(
            model_name="kippotask",
            name="assignee",
            field=models.ForeignKey(
                blank=True, help_text="Assigned to User", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="kippotask",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks_kippotask_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="kippotask",
            name="updated_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks_kippotask_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="kippotaskstatus",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks_kippotaskstatus_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="kippotaskstatus",
            name="updated_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks_kippotaskstatus_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
