# Generated by Django 5.2.1 on 2026-06-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_kippocustomercompliancecheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kippocustomer',
            name='display_as_active',
        ),
    ]
