# Generated by Django 5.2.1 on 2026-06-24 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_kippocustomercompliancecheck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kippocustomer',
            name='display_as_active',
        ),
        migrations.AddField(
            model_name='kippocustomercompliancecheck',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified the compliance check. Stamped from the acting admin when verified is set; cleared when unset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_verified_by', to=settings.AUTH_USER_MODEL, verbose_name='反社チェック確認者'),
        ),
    ]
