# Generated by Django 5.2.1 on 2026-06-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_kippocustomer_display_as_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippocustomer',
            name='contract_folder_url',
            field=models.URLField(blank=True, default='', help_text="Link to the customer's contract documents folder (drive, etc.)", verbose_name='契約フォルダURL'),
        ),
    ]
