# Generated by Django 2.2.9 on 2020-01-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190730_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippoorganization',
            name='slack_api_token',
            field=models.CharField(blank=True, default=None, help_text='REQUIRED if slack channel reporting is desired', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='kippoorganization',
            name='slack_bot_iconurl',
            field=models.URLField(blank=True, default=None, help_text='URL link to slack bot display image', null=True),
        ),
        migrations.AddField(
            model_name='kippoorganization',
            name='slack_bot_name',
            field=models.CharField(blank=True, default='kippo', help_text='REQUIRED if slack channel reporting is desired', max_length=60, null=True),
        ),
    ]
