# Generated by Django 2.1.1 on 2018-10-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180904_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippouser',
            name='is_github_outside_collaborator',
            field=models.BooleanField(default=False, help_text='Set to True if User is an outside collaborator'),
        ),
    ]
