# Generated by Django 2.1.3 on 2019-01-16 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('octocat', '0003_auto_20190116_1107'),
        ('accounts', '0003_kippouser_is_github_outside_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippoorganization',
            name='default_labelset',
            field=models.ForeignKey(blank=True, default=None, help_text='If defined newly identified GithubRepositorie will AUTOMATICALLY have this LabelSet assigned', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='octocat.GithubRepositoryLabelSet'),
        ),
    ]
