# Generated by Django 2.2.28 on 2022-10-03 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20200330_1202"),
    ]

    operations = [
        migrations.AddField(
            model_name="kippoorganization",
            name="fiscalyear_start_month",
            field=models.PositiveSmallIntegerField(
                default=4, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
