# Generated by Django 2.2.2 on 2019-06-06 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_kippoorganization_default_labelset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kippouser',
            name='is_developer',
        ),
        migrations.RemoveField(
            model_name='kippouser',
            name='is_project_manager',
        ),
        migrations.RemoveField(
            model_name='kippouser',
            name='organization',
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('closed_datetime', models.DateTimeField(editable=False, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email address with Organization', max_length=254, null=True)),
                ('is_project_manager', models.BooleanField(default=False)),
                ('is_developer', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=False, help_text='Works Sunday')),
                ('monday', models.BooleanField(default=True, help_text='Works Monday')),
                ('tuesday', models.BooleanField(default=True, help_text='Works Tuesday')),
                ('wednesday', models.BooleanField(default=True, help_text='Works Wednesday')),
                ('thursday', models.BooleanField(default=True, help_text='Works Thursday')),
                ('friday', models.BooleanField(default=True, help_text='Works Friday')),
                ('saturday', models.BooleanField(default=False, help_text='Works Saturday')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_organizationmembership_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.KippoOrganization')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_organizationmembership_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='kippouser',
            name='memberships',
            field=models.ManyToManyField(blank=True, default=None, to='accounts.OrganizationMembership'),
        ),
    ]
