# Generated by Django 5.2.1 on 2025-05-15 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_kippoorganization_fiscalyear_start_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationmembership',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emaildomain',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emaildomain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emaildomain',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kippoorganization',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kippoorganization',
            name='default_task_category',
            field=models.CharField(blank=True, default='study', help_text='Default category to apply to KippoTask objects', max_length=256),
        ),
        migrations.AlterField(
            model_name='kippoorganization',
            name='google_forms_project_survey_projectid_entryid',
            field=models.CharField(blank=True, default='', help_text='"Project Identifier" field in survey (ex: "entry:123456789")', max_length=255),
        ),
        migrations.AlterField(
            model_name='kippoorganization',
            name='google_forms_project_survey_url',
            field=models.URLField(blank=True, default='', help_text='If a "Project Survey" is defined, include here'),
        ),
        migrations.AlterField(
            model_name='kippoorganization',
            name='slack_api_token',
            field=models.CharField(blank=True, default='', help_text='REQUIRED if slack channel reporting is desired', max_length=60),
        ),
        migrations.AlterField(
            model_name='kippoorganization',
            name='slack_bot_iconurl',
            field=models.URLField(blank=True, default='', help_text='URL link to slack bot display image'),
        ),
        migrations.AlterField(
            model_name='kippoorganization',
            name='slack_bot_name',
            field=models.CharField(blank=True, default='kippo', help_text='REQUIRED if slack channel reporting is desired', max_length=60),
        ),
        migrations.AlterField(
            model_name='kippoorganization',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kippouser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='kippouser',
            name='github_login',
            field=models.CharField(blank=True, default='', help_text='Github Login username', max_length=100),
        ),
        migrations.AlterField(
            model_name='kippouser',
            name='memberships',
            field=models.ManyToManyField(blank=True, default=None, through='accounts.OrganizationMembership', through_fields=('user', 'organization'), to='accounts.kippoorganization'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Email address with Organization', max_length=254),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalholiday',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together={('user', 'organization')},
        ),
        migrations.CreateModel(
            name='OrganizationInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('closed_datetime', models.DateTimeField(editable=False, null=True)),
                ('email', models.EmailField(db_index=True, help_text='Email address to send invite to', max_length=254)),
                ('expiration_date', models.DateField(editable=False, help_text='Date the invite expires')),
                ('is_complete', models.BooleanField(default=False, help_text='True if the invite has been accepted')),
                ('processed_datetime', models.DateTimeField(blank=True, editable=False, help_text='Date the invite was processed', null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.kippoorganization')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
