# Generated by Django 5.2.1 on 2025-05-16 07:12

import accounts.definitions
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_organizationmembership_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalholiday',
            options={'ordering': ['-day'], 'verbose_name': '個人休日', 'verbose_name_plural': '個人休日'},
        ),
        migrations.RenameField(
            model_name='kippoorganization',
            old_name='webhook_secret',
            new_name='github_webhook_secret',
        ),
        migrations.AddField(
            model_name='kippoorganization',
            name='enable_slack_channel_reporting',
            field=models.BooleanField(default=False, help_text='Enable Slack channel reporting for this organization'),
        ),
        migrations.AddField(
            model_name='kippoorganization',
            name='slack_attendance_report_channel',
            field=models.CharField(blank=True, default='#kippo', help_text='Slack channel to post attendance report', max_length=50),
        ),
        migrations.AddField(
            model_name='kippoorganization',
            name='slack_channel_name',
            field=models.CharField(blank=True, default='#kippo', help_text='REQUIRED if slack channel reporting is desired', max_length=60),
        ),
        migrations.AddField(
            model_name='kippoorganization',
            name='slack_command_name',
            field=models.CharField(default='kippo', help_text='Slack command name to use', max_length=15),
        ),
        migrations.AddField(
            model_name='kippoorganization',
            name='slack_signing_secret',
            field=models.CharField(blank=True, default='', help_text='Slack signing secret for this organization', max_length=255),
        ),
        migrations.AddField(
            model_name='kippoorganization',
            name='slack_weekly_project_report_channel',
            field=models.CharField(blank=True, default='#kippo', help_text='Slack channel to post weekly project report', max_length=50),
        ),
        migrations.AddField(
            model_name='kippoorganization',
            name='weekly_project_time_deadline',
            field=models.TimeField(default=datetime.time(12, 5), help_text='Cutoff deadline defining the latest time status will be included in the weekly report'),
        ),
        migrations.AddField(
            model_name='kippouser',
            name='slack_user_id',
            field=models.CharField(blank=True, default='', help_text='Slack User ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='organizationinvite',
            name='is_complete',
            field=models.BooleanField(default=False, editable=False, help_text='True if the invite has been processed'),
        ),
        migrations.CreateModel(
            name='SlackCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField(default=False, help_text='True if the command is valid')),
                ('sub_command', models.CharField(blank=True, default='', help_text='Command that was sent', max_length=255)),
                ('text', models.CharField(blank=True, default='', help_text='Text that was sent', max_length=255)),
                ('response_url', models.URLField(blank=True, default='', help_text='Response URL that was sent', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Payload that was sent')),
                ('processed_datetime', models.DateTimeField(blank=True, help_text='Date the command was processed', null=True)),
                ('organization', models.ForeignKey(help_text='Organization that created the command', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.kippoorganization')),
                ('user', models.ForeignKey(help_text='User that created the command', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date of the attendance record')),
                ('category', models.CharField(blank=True, choices=[('start', 'start'), ('break_start', 'break_start'), ('break_end', 'break_end'), ('end', 'end')], default=accounts.definitions.AttendanceRecordCategory['START'], help_text='Category of the attendance record', max_length=255)),
                ('entry_datetime', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(help_text='Organization that created the command', on_delete=django.db.models.deletion.CASCADE, to='accounts.kippoorganization')),
                ('user', models.ForeignKey(help_text='User that created the command', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source_command', models.ForeignKey(blank=True, help_text='Slack command that created the attendance record', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.slackcommand')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
