# Generated by Django 5.2.1 on 2025-05-17 06:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_personalholiday_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kippouser',
            name='slack_user_id',
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='slack_user_id',
            field=models.CharField(blank=True, default='', help_text='Slack user ID', max_length=100),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='slack_username',
            field=models.CharField(blank=True, default='', help_text='Slack username', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Date of the attendance record'),
        ),
    ]
