# Generated by Django 5.2.1 on 2025-05-25 11:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_endattendancerecord_startattendancerecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='slack_image_url',
            field=models.URLField(blank=True, default='', help_text='Slack user image URL'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False, help_text='Date of the attendance record'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='organization',
            field=models.ForeignKey(editable=False, help_text='Organization that created the command', on_delete=django.db.models.deletion.CASCADE, to='accounts.kippoorganization'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='source_command',
            field=models.ForeignKey(blank=True, editable=False, help_text='Slack command that created the attendance record', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.slackcommand'),
        ),
    ]
