# Generated by Django 5.2.1 on 2025-06-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_organizationmembership_slack_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicholiday',
            name='day',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['user_id', 'organization_id'], name='accounts_or_user_id_0c79eb_idx'),
        ),
        migrations.AddIndex(
            model_name='personalholiday',
            index=models.Index(fields=['user_id', 'day'], name='accounts_pe_user_id_97d55a_idx'),
        ),
    ]
