# Generated by Django 5.2.1 on 2026-01-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_publicholiday_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippoorganization',
            name='default_github_project_template',
            field=models.CharField(blank=True, default='', help_text='GitHub ProjectsV2 node ID to use as template when creating projects', max_length=255),
        ),
    ]
