# Generated by Django 5.2.1 on 2026-01-27 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_kippoorganization_default_github_project_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kippoorganization',
            name='default_columnset',
        ),
    ]
