# Generated by Django 5.2.1 on 2026-05-10 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_kippoorganization_default_columnset'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippoorganization',
            name='project_assignment_member_soft_ceiling',
            field=models.PositiveSmallIntegerField(default=75, help_text="Target maximum total project utilization percentage per organization member. Drives the suggester's per-pattern percentage cap so proposed assignments leave headroom for non-project work. 1-100; the absolute hard cap remains 100%.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
