# Generated by Django 5.2.1 on 2026-05-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_project_assignment_member_soft_ceiling'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippoorganization',
            name='calendar_email',
            field=models.EmailField(blank=True, default='', help_text="Optional. Resource Calendar email (c_xxx@resource.calendar.google.com). When set, it is added as a forced attendee (the 'add' parameter) of project MTG calendar-template URLs so created meeting minutes are collected per-project.", max_length=254),
        ),
    ]
