# Generated by Django 5.2.1 on 2026-05-29 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_kippoorganization_calendar_email'),
        ('projects', '0037_kippoproject_billing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippoorganization',
            name='default_columnset',
            field=models.ForeignKey(blank=True, default=None, help_text='Default ProjectColumnSet applied to new projects created for this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.projectcolumnset'),
        ),
    ]
