# Generated by Django 5.2.1 on 2026-06-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_kippoorganization_default_columnset'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippoorganization',
            name='weekly_effort_close_offset_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='週間稼働の締めまでの日数: 月内最後の有効入力日 (最終月曜) からこの日数の経過で当月分の編集を締める (kippo#33 / T17)'),
        ),
    ]
