# Generated by Django 5.2.1 on 2026-06-24 02:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_kippoorganization_weekly_effort_close_offset_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='kippoorganization',
            name='timezone',
            field=models.CharField(default='Asia/Tokyo', help_text='IANA timezone used for fiscal-year / date determination (default: Asia/Tokyo / JST).', max_length=64, validators=[accounts.models.validate_timezone], verbose_name='タイムゾーン'),
        ),
    ]
