# Generated by Django 5.2.1 on 2026-08-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_kippoorganization_timezone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Organization admin: may invite members to this organization'),
        ),
    ]
