# Generated by Django 5.2.1 on 2026-05-10 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_kippoorganization_project_assignment_member_soft_ceiling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('closed_datetime', models.DateTimeField(editable=False, null=True)),
                ('category', models.CharField(choices=[('bug', 'bug'), ('feature', 'feature'), ('general', 'general'), ('other', 'other')], default='general', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('reviewed_datetime', models.DateTimeField(blank=True, null=True)),
                ('review_action', models.CharField(blank=True, choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('duplicate', 'duplicate'), ('needs_info', 'needs_info'), ('issue_created', 'issue_created')], max_length=20, null=True)),
                ('github_issue_url', models.URLField(blank=True, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='accounts.kippoorganization')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_datetime'],
            },
        ),
    ]
